services:
  # --- BASE DE DATOS (POSTGRESQL) ---
  db:
    image: postgres:15-alpine
    container_name: svi_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 561834927Garyn
      POSTGRES_DB: svi_db
    ports:
      - "5433:5432" # El puerto de tu PC será el 5433
    volumes:
      - svi_pgdata:/var/lib/postgresql/data # Volumen independiente
      - ./backend/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d svi_db" ] # ◄ Corregido a svi_db
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND (FASTAPI) ---
  backend:
    build: ./backend
    container_name: svi_fastapi_backend # ◄ Nombre único
    restart: always
    ports:
      - "8001:8000" # ◄ Cambiado a 8001 en tu PC
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  # --- FRONTEND (REACT + VITE) ---
  frontend:
    build: ./frontend
    container_name: svi_react_vite_frontend # ◄ Nombre único
    restart: always
    ports:
      - "5174:5173" # ◄ Cambiado a 5174 en tu PC
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  svi_pgdata: # ◄ Volumen único para que no compartan datos de disco
